[package]
name = "cosmic-process-killer"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "COSMIC applet to kill frozen processes"
repository = "https://github.com/marcossl10/cosmic-process-killer"
default-run = "cosmic-applet-process-killer"

[lib]
name = "cosmic_applet_process_killer"
path = "src/lib.rs"

[[bin]]
name = "cosmic-process-killer"
path = "src/main.rs"

[[bin]]
name = "cosmic-process-killer-standalone"
path = "src/bin/standalone.rs"

[dependencies]
futures-util = "0.3.31"
i18n-embed-fl = "0.10"
rust-embed = "8.7.2"
tokio = { version = "1.48.0", features = ["full"] }
sysinfo = "0.32"
nix = { version = "0.29", features = ["signal"] }

[dependencies.i18n-embed]
version = "0.16"
features = ["fluent-system", "desktop-requester"]

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
# See https://github.com/pop-os/libcosmic/blob/master/Cargo.toml for available features.
features = [
    # Applet support
    "applet",
    "applet-token",
    # Uses cosmic-settings-daemon to watch for config file changes
    "dbus-config",
    # Support creating additional application windows.
    "multi-window",
    # Uses tokio as the executor for the runtime
    "tokio",
    # Add Wayland support to winit
    "wayland",
    # Windowing support for X11, Windows, Mac, & Redox
    "winit",
]

# Uncomment to test a locally-cloned libcosmic
# [patch.'https://github.com/pop-os/libcosmic']
# libcosmic = { path = "../libcosmic" }
# cosmic-config = { path = "../libcosmic/cosmic-config" }
# cosmic-theme = { path = "../libcosmic/cosmic-theme" }
